name: Terraform Destroy

on:
  workflow_dispatch: # Manually triggered

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::171171308751:role/github-action  # Replace with your real role ARN
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd Terraform/all
          terraform init  

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: Terraform/all

